### ISSUE TITLE
Unhandled rejection ParserError

### ISSUE THREAD

**Issue by meet2amit** [codemanki/cloudscraper#192]
Hello team
when we try today we got this message this already work before 2 days

`var cloudscraper = require('cloudscraper');

cloudscraper.get('https://app.smartapartmentdata.com/XML/GetInventory.aspx?licenseKey=xxxxxxxxxxxxxxx', function(error, response, body) {
  if (error) {
    console.log('Error occurred');
  } else {
    console.log(body, response);
  }
});`

### Check the detailed exception message that follows for the cause.

SyntaxError: Challenge evaluation failed: Unexpected token |
    at solveChallenge (F:\phantanjs\scraper2\node_modules\cloudscraper\index.js:294:21)
    at processRequestResponse (F:\phantanjs\scraper2\node_modules\cloudscraper\index.js:188:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (F:\phantanjs\scraper2\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (F:\phantanjs\scraper2\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by codemanki** [comment]
Hi Amit. Thanks for reporting this issue. I have released a new version with a fix literally 20 minutes ago. Please update to the `cloudscraper@3.8.0`, it should work now

**Comment by meet2amit** [comment]
ok thank you for your quick update we will check and let you know

**Comment by meet2amit** [comment]
Sorry to said you
But still getting same error can you please check one more time at if any change need?

**Comment by pro-src** [comment]
@meet2amit The recent fix works but theres a bug related to timeout parsing. Specify the timeout.
```js
var cloudscraper = require('cloudscraper').defaults({ cloudflareTimeout: 4000 })
```

And copy headers from your web browser to use with cloudscraper.
```js
var cloudscraper = rquire('cloudscraper').defaults({ headers: headers })
```

See https://github.com/codemanki/cloudscraper/tree/master/examples for more example

We'll have this fixed very shortly so be on the lookout for v3.8.1

**Comment by codemanki** [comment]
3.9.0 is out with a fix!

**Comment by codemanki** [comment]
Aaaaaand 3.9.1 is also out with an additional fix

**Comment by meet2amit** [comment]
ok let me check

**Comment by meet2amit** [comment]
Wrokin

> Aaaaaand 3.9.1 is also out with an additional fix

working now 

Really Appreciate your quick solution 

Thank you
